### ISSUE TITLE
Interested by a working mic button ?

### ISSUE THREAD

**Issue by Oliv4945** [alexylem/jarvis-ui#10]
I am still waiting for my Respeaker, so I built an headless Jarvis server.
In order to have voice interaction with it, I linked the microphone button in the Jarvis-ui to Bing STT.

What I did:
1.  Use Microsoft STT javascript library
2.  Hide Jarvis-ui behind a reverse proxy to manage ssl (Seems to be required by Chrome to use microphone)
3.  Switch Jarvis-api to ssl (Required because http & https can't be mixed)
4. Minor other code modifications

@alexylem, do you have a plan for this button, or do you want me to clean my code and do a PR ?
I think it is easy to manage Jarvis-ui to send ssl without reverse proxy, but it need to generate a self signed certificate, which might confuse people because they will get warnings. A workaround might be to use Let's Encrypt but I don't know if we can generate a certificate without a domain name.

PS : It is not clear if you use English or French for all discussions on Jarvis, let me know :p

**Comment by alexylem** [comment]
Hello @Oliv4945 and thanks a lot for sharing :+1: 
English is better, but community is primarily French, so no particular rule!

I was planning to use Chrome voice recognition:
https://www.google.com/intl/en/chrome/demos/speech.html
https://developers.google.com/web/updates/2013/01/Voice-Driven-Web-Apps-Introduction-to-the-Web-Speech-API
But any other browser agnostic solution is better, like yours.

I've already been fighting with SSL certificate using self generated one, but the red alerts (despite it works) are a killer to me and most other users out there. I'd like to have a real signed one, but it seems we need to pay for this. And btw I have a domain for Jarvis:
http://domotiquefacile.fr
So unless having Jarvis-UI sitting on my server, I don't see any simple solution...

PR is more than welcome, but it should be super easy for lamdba users to set this up (this is the philosophy of the project).
What do you think?

**Comment by Oliv4945** [comment]
> I'd like to have a real signed one, but it seems we need to pay for this. And btw I have a domain for Jarvis

I checked and SSL certificates can not be issued for privates IP, so I don't think my solution will work "out of the box" for most people.
The error I am [getting ](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins)is Chrome only for now but it is a recommandation from [W3C](https://w3c.github.io/webappsec-secure-contexts/), so all browser will do that sooner or later.

>I was planning to use Chrome voice recognition:

I just tried their demo within an insecure webserver...it works ! Their is a lack of uniformity in Chrome API :(

I will check if their is other open source projects with a solution to record audio.

**Comment by alexylem** [comment]
I am now experimenting google chrome speech api. I published it on my website and it works, play with it here (only working from Chrome obviously...)
http://domotiquefacile.fr/chrome_speech_api/webspeechdemo.html
Now trying to have it running on my raspberry pi...

**Comment by alexylem** [comment]
Works locally from my Jarvis-UI python webserver, no certificate 👍 
![image](https://cloud.githubusercontent.com/assets/11017174/25487838/b18acad4-2b65-11e7-8ddf-3523a845935e.png)
Working now on a quick & dirty implementation

**Comment by alexylem** [comment]
@Oliv4945 and @RobyBioloid
Here is a working prototype, watch out the reactivity, amazing 😄  no SSL nothing:
https://youtu.be/GTVlH8OR3aQ

**Comment by alexylem** [comment]
So disappointed, does not work on iOS Chrome 😢

**Comment by alexylem** [comment]
For iOS I have a new idea: alexylem/jarvis#569
Keeping this ticket for Desktop Chrome (I think Android Chrome will also work).

**Comment by Oliv4945** [comment]
Yes, when I tried it was working in Android

**Comment by alexylem** [comment]
Here is the final demo, it automatically detects end of speech and sends to Jarvis.
I may have a hot key in the future but i'm already pretty happy with the result.
Have a look!
https://youtu.be/xV3RfVNwzwc
I'll soon release the update on Jarvis-UI plugin.
⚠️  Again: only works on Desktop / Android Chrome.
