### ISSUE TITLE
Acces Jarvis-ui depuis le navigateur

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis-ui#12]
Bonjour,

Je n'arrive plus à accéder à Jarvis depuis le navigateur à l'adresse local 192.168.1.99:8090

La page tente de se connecter mais rien ne s'affiche

**Comment by Oliv4945** [comment]
Si tu affiches la console, est-ce que tu as une erreur affichée?F12 sur beaucoup de navigateurs.

**Comment by RobyBioloid** [comment]
Petite précision.

Je n'arrive pas à accéder à Jarvis en local via le navigateur quand il est **en mode service**.

**Comment by alexylem** [comment]
>Je n'arrive pas à accéder à Jarvis en local via le navigateur quand il est en mode service.

Tu veux dire `./jarvis.sh -b` ? Ca marche avec `./jarvis.sh -n` ?
J'imagine que tu as testé depuis une autre machine sans succès?
Pourrais-tu coller le contenu de Jarvis lancé en mode troubleshooting, surtout le début quand il affiche:
```shell
Starting RestAPI server on http://192.168.1.20:8080
Starting User Interface on http://192.168.1.20:8081
```
PS: je viens de tester chez moi ca marche.
Alex.

**Comment by W1tch3d** [comment]
Bonjour, 
je rencontre le même problème chez moi: 
j'ai une erreur sur la jarvis-UI, (sur la page web) qui s'affiche comme une notification:
```
Error 501 from http://192.168.1.18:8081: error;
Error response
Error code 501.

Message: Unsupported method ('POST').

Error code explanation: 501 = Server does not support this operation. ;Unsupported method ('POST')
```

depuis la CLI, quand je lance en mode debug ou en normal (pas en service) je n'ai pas de message d'erreur
![capture du 2017-05-05 15-24-05](https://cloud.githubusercontent.com/assets/28442913/25747202/edc6c740-31a6-11e7-82ca-6cc6832221e1.png)

suis en RPI3 et raspbian8

**Comment by alexylem** [comment]
@W1tch3d  Tu dois mettre le port de Jarvis-API, pas celui de Jarvis-UI...
Donc remplace `8081` par `8080` dans Client Settings (la popup qui est ouverte sur ta copie d'écran).

**Comment by W1tch3d** [comment]
no more success, j'ai un message d'erreur qui s'affiche pareil dans les notifs: 
`Connection error. Verify Jarvis is started, has jarvis-api installed and check api port in Client settings`

**Comment by W1tch3d** [comment]
je viens de comprendre mon erreur originelle -> jarvis-API est nécessaire (ok, je sors...)
Une fois installé, ca marche nickel

**Comment by alexylem** [comment]
@W1tch3d ok je vais rajouter une vérification lors de l'installation de Jarvis-UI que Jarvis-API est installé.
@RobyBioloid des news de ton côté suite à [mon commentaire](https://github.com/alexylem/jarvis-ui/issues/12#issuecomment-298329668)?

**Comment by W1tch3d** [comment]
@alexylem bravo pour la réactivité, aussitôt dit, aussitôt commit. Et merci pour le support!

**Comment by RobyBioloid** [comment]
Je viens de tester et ça à l'air de fonctionner maintenant. Je ne sais pas pourquoi des fois ça ne fonctionne pas.

**Comment by alexylem** [comment]
@RobyBioloid je viens de réaliser sur ton premier post que tu tentes d'accéder à 
http://192.168.1.99:8090. J'imagine que tu sais que le port par défaut de Jarvis-UI est `8080` et j'en déduis que c'est toi qui l'a changé dans la config... sinon c'est normal 😄 

Je ferme, si tu arrive à reproduire, envoies un max d'info, surtout la log de Jarvis (si lancé en background: `jarvis.log`)

**Comment by RobyBioloid** [comment]
oui j'ai modifié car le port 8080 est déjà utilisé par Mjpg-Streamer.
