### ISSUE TITLE
changement de port

### ISSUE THREAD

**Issue by AlainGr** [alexylem/jarvis-ui#13]
Bonjour,
La modification des ports dans le config.sh ne semble pas prise en compte. Ayant domticz installé qui prend le port 8080, j'ai modifié les ports de jarvis-api et de jarvis-ui. En ouvrant l'interface, j'avais un mix domoticz / jarvis-ui non fonctionnel. En bidouillant un peu (mes connaissances sont très limitées) je suis allé modifier le fichier my.js en modifiant le port par défaut (8080) par le nouveau port de jarvis-api. Tout fonctionne maintenant parfaitement. Si cela peut aider (encore bravo pour le travail réalisé)

**Comment by alexylem** [comment]
@AlainGr 
Le fichier `config.sh` de Jarvis-UI sert à changer le port sur lequel l'interface Jarvis-UI sera accessible. Pour changer le port de Jarvis-API, il faut:
1. Changer le port de Jarvis-API via la configuration du plugin Jarvis-API
2. Lancer Jarvis-UI (ouvrir l'interface web après avoir lancé Jarvis), puis changer le port dans la configuration de l'interface web de Jarvis-UI.
