### ISSUE TITLE
Error 200 from http://192.168.0.17:8080: parsererror;

### ISSUE THREAD

**Issue by UnleashSpirit** [alexylem/jarvis-ui#18]
Bonjour,

Je viens d'installer Jarvis sur un Rpi 2 (sans micro pour le moment) ainsi que Jarvis UI et API.
L'UI est configuré sur le port 8081 et l'API sur le 8082 (le 8080 étant déjà utilisé par Domoticz)
Starting RestAPI server on http://192.168.0.17:8082
Starting User Interface on http://192.168.0.17:8081

Lorsque je me connecte avec Chrome (Version 63.0.3239.84) depuis mon PC sur http://192.168.0.17:8081 j'ai une erreur : Error 200 from http://192.168.0.17:8080: parsererror;

![image](https://user-images.githubusercontent.com/6216968/34575351-b5f148d8-f17a-11e7-85f9-49d00abcd33f.png)
![image](https://user-images.githubusercontent.com/6216968/34575378-dad56fd0-f17a-11e7-8574-34ff5d78bb5d.png)

En fouinant (très) vite fait j'ai changé le port dans le fichier : jarvis-ui/js/my.js@246 pour forcer le port à 8081 (il est à 8080, le par défaut) j'ai une autre erreur, déjà évoqué dans un autre ticket.
![image](https://user-images.githubusercontent.com/6216968/34575490-430ea814-f17b-11e7-86fb-6c6ae52eb517.png)

Si quelqu'un a une idée ? Je suis preneur :)

**Comment by Oliv4945** [comment]
Salut

Au début de ton message tu as Jarvis API qui tourne sur le port 8082, et Jarvis UI sur le port 8081.
Il faut donc indiquer le port 8082 dans le champ "Jarvis-API port" de ta dernière capture d'écran au leu de 8081

**Comment by UnleashSpirit** [comment]
Effectivement ça fonctionne mieux là. Merci !
Par contre ça reste étrange car la deuxième capture est faite après modification du code source...
Je n'ai pas accès (le cadre rouge est au dessus et impossible à fermer) à la "roue" de paramètre que je vois une fois que ça fonctionne
![image](https://user-images.githubusercontent.com/6216968/34620241-11b42364-f245-11e7-93b9-0fd9b79d506c.png)

En tout cas mon souci est résolu.
Encore merci
