### ISSUE TITLE
J'ai un problème de mémorisation de port...

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [alexylem/jarvis-ui#3]
Bonjour à chaque fois que j'ouvre la page UI il ne me mémorise pas le port  car j'ai du le changer à cause d'un doublon d'utilisation sur mon Raspberry.

Dans le Config.sh de Jarvis-UI  j'ai bien modifié:
jv_pg_ui_port=8088 # port for Jarvis Web Interface 
donc là ok j'accède sans problème à la page http://192.168.1.XX:8088 . 

Dans le config de Jarvis-API j'ai bien modifé 
 jv_pg_api_port=8087 # port for Jarvis RestAPI Server
et là il me faut quand même aller modifié le port en ouvrant la page UI, puis Client Settings et modifier  Javis-API Port en 8087 (il reste sur 8080)  qui ne récupère pas la valeur.

**Comment by alexylem** [comment]
Voila c'est corrigé. Mettez à jour:
```shell
$> ./jarvis.sh -u
```
